export { Details } from './components/Details/Details';
export { Filter } from './components/Filter/Filter';
export { Form } from './components/Form/Form';
export type { FormInterface } from './components/Form/Form';
export { TableEndless } from './components/TableEndless/TableEndless';
export { TablePagination } from './components/TablePagination/TablePagination';
export { TableBar } from './components/TableBar/TableBar';
export { ChatBar } from './components/ChatBar/ChatBar';
export type { ColumnConfig, FilterConfig, FilterOption, Field, FieldOption } from './types/types';
export { ColumnType, FilterType, FieldType } from './types/types';
export { useCrudModals } from './components/CrudModals/useCrudModals';
export { ConnectedTable } from './components/ConnectedTable/ConnectedTable';
console.log('react-connected-components ->', '0.0.177');
